import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BackgroundProvider from "@/clientProvider/provider";
import { Providers } from "@/clientProvider/queryclient";
import HydrateQueryClient from "@/clientProvider/hydration";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <BackgroundProvider>
            <HydrateQueryClient>{children}</HydrateQueryClient>
          </BackgroundProvider>
        </Providers>
      </body>
    </html>
  );
}
